### ISSUE TITLE
Centerpoint in middle of artboard

### ISSUE THREAD

**Issue by marathonworks** [elcontraption/illustrator-point-coordinate-exporter#4]
Hi! Love your script. I was wondering if it is possible to adjust the center point. Currently all points are calculated from the left top of the artboard. For my particular project I need the [0,0] point to be in the middel of a square artboard, so points can have a negative value.

I tried adjusting the artboard in jour `exporter.js`, but I have the feeling it's being ignored.

`Exporter.prototype = {
	    document: {},
	    artboard: { x: -200, y: -200, w: 400, h: 400 },
	    output: {
	        layers: []
	    }
	};`

Any advice?

**Comment by elcontraption** [comment]
Currently, those `x`, `y`, `w`, and `h` values you're setting in the `prototype` are being overwritten in the `getArtboardInfo` method. I'm not able to dive into this at the moment, at least until I finish another project on my plate, but you could try fiddling with the `getArtboardInfo` method, maybe try:

```js
this.artboard.x += artboard.artboardRect[0];
this.artboard.y += artboard.artboardRect[1];
```

So that your `x` and `y` values are added in. 

Alternatively, you could add/subtract the appropriate value on the other end, wherever you're using the output from this script. 

Let me know if you get it to work, submit a PR or tell me what you did and I'll incorporate it. This would be a nice addition. Thanks!

**Comment by marathonworks** [comment]
thx for the direction! With some help I have changed the following part:

`paths.push({"point": [(path.position[0]+path.width/2)/100,0.00,(path.position[1]+path.height/2)/100]})`

Instead of 200 px I needed 2.0, hence the divide by hundred.

**Comment by elcontraption** [comment]
Awesome, I'm glad you found a solution. This was kind of a quick one-off script that I needed for a client project, and I wish I had time to make it more flexible.
